spring:
  application:
    name: mmw

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mmw}
    username: ${DB_USERNAME:mmw}
    password: ${DB_PASSWORD:mmw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-flash-latest
  base-url: https://generativelanguage.googleapis.com

stt:
  language-code: ko-KR
  model: latest_long
  sample-rate-hertz: 16000

tts:
  language-code: ko-KR
  voice-gender: FEMALE
  speaking-rate: 1.0

gcs:
  bucket-name: ${GCS_BUCKET_NAME:mmw-audio-test-000000}

gcp:
  credentials-path: ${GCP_CREDENTIALS_PATH:gcp-key.json}
  project-id: mmw-project-000000